-- SCHEMA: hospital

-- DROP SCHEMA IF EXISTS hospital ;

CREATE SCHEMA IF NOT EXISTS hospital
    AUTHORIZATION hospital_admin;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA hospital
TO hospital_admin;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA hospital TO hospital_admin;

ALTER DEFAULT PRIVILEGES FOR ROLE admin IN SCHEMA hospital
GRANT INSERT, SELECT, UPDATE, DELETE, TRIGGER, TRUNCATE ON TABLES TO hospital_admin;

ALTER DEFAULT PRIVILEGES FOR ROLE admin IN SCHEMA hospital
GRANT USAGE, SELECT ON SEQUENCES TO hospital_admin;

ALTER DEFAULT PRIVILEGES FOR ROLE admin IN SCHEMA hospital
GRANT EXECUTE ON FUNCTIONS TO hospital_admin;

ALTER DEFAULT PRIVILEGES FOR ROLE admin IN SCHEMA hospital
GRANT USAGE ON TYPES TO hospital_admin;